module.exports = {
    NOT_ENOUGH_RESOURCES: 1,
    NO_VALID_PARTS_SPECIFIED: 2,
    TOO_MANY_PARTS: 3,
    CANNOT_CREATE: 4,
    CANNOT_MOVE: 5,
    INVALID_COORDINATES: 6,
    COORDINATES_NOT_ACCESSIBLE: 7,
    NOT_ALLOWED: 8,
    INVALID_COORDINATES: 9,
}